### ISSUE TITLE
Пушка

### ISSUE THREAD

**Issue by Ainoss** [Berdash/infa_2019_berdashkevich#1]
Проверил задачу, в целом неплохо, есть некоторая интерактивность :)
Однако не обошлось и без проблем: два существенных бага описал в построчных комментариях к коммиту; стиль написание кода отличается от общепринятого (в основном это касается пробелов вокруг операторов, см. https://pep8.ru/doc/pep8/)

Есть смысл доработать, оставляю это на ваше усмотрение. Пока - хор(6)

**Comment by Berdash** [comment]
"Есть смысл доработать, оставляю это на ваше усмотрение. Пока - хор(6)"

Как может измениться оценка при доработке?


ср, 11 дек. 2019 г. в 00:04, Aleksandr Kayda <notifications@github.com>:

**Comment by Ainoss** [comment]
На балл уж точно можно повысить

**Comment by Berdash** [comment]
Я вроде поправил, кроме списка ball. Нет идей как реализовать

**Comment by Ainoss** [comment]
Принято!
